[docs] #95: Update Python asset metadata example
hyperledger/iroha-2-docs pull request #104
Opened 2022-08-10 07:56 UTC by outoftardis

2022-08-10 08:04 UTC, WRRicht3r approved these changes

2022-08-11 07:39 UTC, 6r1d requested changes
`asset.DefinitionId` still requires an `asset` import.

2022-08-11 07:42 UTC, appetrosyan approved these changes

2022-08-11 07:43 UTC, appetrosyan requested changes

2022-08-11 07:43 UTC, appetrosyan commented on src/guide/python.md
> -import iroha2.data_model.asset as asset
Please revert.

2022-08-11 07:45 UTC, outoftardis commented on src/guide/python.md
> +from iroha2.sys.iroha_data_model import Value
```suggestion
import iroha2.data_model.asset as asset
from iroha2.sys.iroha_data_model import Value
```

2022-08-11 07:48 UTC, appetrosyan approved these changes

2022-08-11 07:49 UTC, merged