[docs] #85: Add UML diagrams
hyperledger/iroha-2-docs pull request #148
Opened 2022-09-01 03:11 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

I've added a couple of diagrams, not covering everything yet, just to make sure this is the right format.

2022-09-02 14:10 UTC, appetrosyan commented on src/guide/diagrams-src/domain-account-asset.puml
> +@enduml
Consider adding newlines at end of file. This isn't strictly necessary, but every other file has a newline at the end.

2022-09-02 14:10 UTC, appetrosyan approved these changes

2022-09-05 07:49 UTC, WRRicht3r requested changes

2022-09-05 07:49 UTC, WRRicht3r commented on src/guide/advanced/permissions.md
> +roles can be granted using `Grant` instruction and revoked using `Revoke`
```suggestion
roles can be granted using. the `Grant` instruction and revoked using the `Revoke`
```

2022-09-05 07:49 UTC, WRRicht3r commented on src/guide/advanced/permissions.md
> +Before granting a role to an account, a role should first be registered.
```suggestion
Before granting a role to an account, the role should be registered first.
```

2022-09-05 07:49 UTC, WRRicht3r commented on src/guide/advanced/queries.md
> +[metadata](../objects/metadata.md) as the metadata key is used to sort
```suggestion
[metadata](../objects/metadata.md), as the metadata key is used to sort
```

2022-09-05 07:49 UTC, WRRicht3r commented on src/guide/objects/hierarchy.md
> +of Iroha. In the stable version, permission tokens are stored not within
```suggestion
of Iroha. In the stable version, permission tokens aren't stored within
```

2022-09-05 07:49 UTC, WRRicht3r commented on src/guide/objects/metadata.md
> +[role](../advanced/permissions.md#permission-groups-roles) for accessing
```suggestion
[role](../advanced/permissions.md#permission-groups-roles) for accessing the
```

2022-09-05 08:03 UTC, 6r1d approved these changes
LGTM, ping me after addressing Willam's changes if GitHub requires a re-approval.

2022-09-05 08:15 UTC, outoftardis commented on src/guide/advanced/permissions.md
> +roles can be granted using `Grant` instruction and revoked using `Revoke`
```suggestion
roles can be granted using the `Grant` instruction and revoked using the `Revoke`
```

2022-09-05 09:26 UTC, WRRicht3r approved these changes

2022-09-06 05:50 UTC, merged