[docs] #170: Update client config page
hyperledger/iroha-2-docs pull request #176
Opened 2022-09-15 12:23 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

Closes #170

2022-09-15 12:49 UTC, WRRicht3r requested changes

2022-09-15 12:49 UTC, WRRicht3r commented on src/guide/configure/client-configuration.md
> +for handling incoming and outgoing connections. You should also add either
```suggestion
for handling incoming and outgoing connections. You should also add the prefix
```

2022-09-15 12:49 UTC, WRRicht3r commented on src/guide/configure/client-configuration.md
> +should set up a domain for public blockchains. Bare connections[^1] are
```suggestion
should also set up a domain for public blockchains. Bare connections[^1] are
```

2022-09-16 09:52 UTC, outoftardis commented on src/guide/configure/client-configuration.md
>  worry about, is that the account must exist in the blockchain. In the
```suggestion
worry about is that the account must exist in the blockchain. In the
```

2022-09-16 09:59 UTC, WRRicht3r approved these changes

2022-09-19 11:20 UTC, astrokov7 approved these changes

2022-09-19 11:52 UTC, merged