[docs] #174: Update documentation after RC-9 (LTS)
hyperledger/iroha-2-docs pull request #195
Opened 2022-10-11 07:33 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

- Closes #156: updated `FindTransaction` output
- Closes #183: added info about genesis account keys
- Closes #186: added info about parameters in permission token definitions
- Closes #187: updated client config example
- added info about configuration types (from condig.md in the main repo)
- updated references about different versions
- updated docker-compose file
- updated peer config page
- added a page with all config examples present (to avoid copy-pasting, configs are stored in json files and included in other md)
- Partially addressed #184: reflecting the changes in object structure

Will be added to this pr as well:
- #140, #185, #188, #189

2022-10-12 14:02 UTC, appetrosyan commented on src/guide/configure/peer-configuration.md
> +KURA is the "warehouse" engine of Iroha. The `BLOCK_STORE_PATH` specifies
```suggestion
_Kura_ is the persistent storage engine of Iroha (Japanese for _warehouse_). The `BLOCK_STORE_PATH` specifies
```

2022-10-12 14:26 UTC, WRRicht3r requested changes

2022-10-12 14:26 UTC, WRRicht3r commented on src/guide/configure/intro.md
> +Read about the difference in underlying [types for configuration options](./configuration-types.md).
```suggestion
Read about the difference between underlying [types for configuration options](./configuration-types.md).
```

2022-10-12 14:26 UTC, WRRicht3r commented on src/guide/configure/peer-configuration.md
> +You can do this via configuration file (`ACCOUNT_PUBLIC_KEY`, `ACCOUNT_PRIVATE_KEY`) or environment variables (`IROHA_GENESIS_ACCOUNT_PUBLIC_KEY`, `IROHA_GENESIS_ACCOUNT_PRIVATE_KEY`).
```suggestion
You can do this via the configuration file (`ACCOUNT_PUBLIC_KEY`, `ACCOUNT_PRIVATE_KEY`) or environment variables (`IROHA_GENESIS_ACCOUNT_PUBLIC_KEY`, `IROHA_GENESIS_ACCOUNT_PRIVATE_KEY`).
```

2022-10-13 08:08 UTC, outoftardis commented on src/guide/diagrams-src/domains-example.puml
> +  id = "narnia"
changed the example

2022-10-17 05:55 UTC, appetrosyan approved these changes

2022-10-17 07:34 UTC, merged