[docs] #159, #171, #179: Update config sections
hyperledger/iroha-2-docs pull request #213
Opened 2022-10-25 10:14 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

Closes #159 
Closes #171 
Closes #179

2022-10-25 10:21 UTC, 6r1d approved these changes
LGTM

2022-10-25 10:39 UTC, WRRicht3r requested changes

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/advanced/isi.md
> +| [SetKeyValue/RemoveKeyValue](#setkeyvalue-removekeyvalue) | Update metadata of blockchain objects.            |
```suggestion
| [SetKeyValue/RemoveKeyValue](#setkeyvalue-removekeyvalue) | Update blockchain object metadata.            |
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/advanced/running-iroha-on-bare-metal.md
> +offer you instructions for running Iroha on bare metal without going into
```suggestion
offer you instructions to run Iroha on bare metal without going into
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/advanced/running-iroha-on-bare-metal.md
> +details about various configuration options available to you.
```suggestion
details about various configuration options available.
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/advanced/running-iroha-on-bare-metal.md
> +You will find the complete list of options in
```suggestion
The complete list of options is available in the
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/advanced/running-iroha-on-bare-metal.md
>  5.  After you finished editing the configuration file, deploy Iroha by
```suggestion
5.  After you have finished editing the configuration file, deploy Iroha by
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/configure/client-configuration.md
> +You can specify the transaction limits to which each transaction must
```suggestion
You can specify the transaction limits that each transaction must
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/configure/genesis.md
> +new accounts or assets, minting assets. You can also register permission
```suggestion
new accounts or assets, as well as minting assets. You can also register permission
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/configure/genesis.md
> +tokens and roles as well as grant them to the registered accounts.
```suggestion
tokens and roles, as well as grant them to the registered accounts.
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/configure/peer-configuration.md
> +Besides the public and private keys for genesis account, which are the
```suggestion
Aside from the public and private keys for the genesis account, which are
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/configure/peer-configuration.md
> +  connecting to peers
```suggestion
  a connection to peers
```

2022-10-25 10:39 UTC, WRRicht3r commented on src/guide/objects/assets.md
>  Refer to one of the language-specific guide to walk you through the process
```suggestion
Refer to one of the language-specific guides to walk you through the process
```

2022-10-25 13:07 UTC, WRRicht3r approved these changes

2022-10-28 07:41 UTC, appetrosyan requested changes

2022-10-28 07:41 UTC, appetrosyan commented on src/guide/configure/genesis.md
> +`/configs/peer/config.json`. This is the account that will submit the
```suggestion
`configs/peer/config.json`. This is the account that will submit the
```
On Unix the first slash is the root directory. Please revert all instances.

2022-10-28 07:48 UTC, appetrosyan approved these changes

2022-10-28 07:50 UTC, merged