[chore]: Add Google Analytics
hyperledger/iroha-2-docs pull request #244
Opened 2023-01-03 03:20 UTC by 6r1d

This commit adds [Google Analytics](https://analytics.google.com) user activity tracking into Iroha tutorial.
This was requested on standup and would allow to understand what pages users are looking for.

Signed-off-by: 6r1d <vic.6r1d@gmail.com>

2023-01-09 01:50 UTC, 0x009922 requested changes
Please format the code.

2023-03-20 06:30 UTC, appetrosyan approved these changes
In principle looks good, if you still think that we need this, I don't mind merging.

2023-03-31 04:39 UTC, 0x009922 requested changes

2023-03-31 04:39 UTC, 0x009922 commented on .vitepress/config.ts
> +    ],
You don't need this if you use `@gtm-support/vue-gtm`. So, remove it please.

2023-04-17 08:11 UTC, 0x009922 approved these changes

2023-04-18 12:05 UTC, merged