[docs] Extend the glossary
hyperledger/iroha-2-docs pull request #245
Opened 2023-01-03 05:10 UTC by 6r1d

A small extension for the glossary, so the doc is easier to navigate without confusing the user with the terminology.
It is possible to link the assets instead of the glossary for the asset-related part, but I believe the glossary section should be separate.

Signed-off-by: 6r1d <vic.6r1d@gmail.com>

2023-01-03 13:59 UTC, WRRicht3r requested changes

2023-01-03 13:59 UTC, WRRicht3r commented on src/guide/glossary.md
> +These are named after old-fashioned books used for financial records[^1] because of their history.
```suggestion
These are named after old-fashioned books that were used for financial records[^1] because of their history.
```

2023-01-03 13:59 UTC, WRRicht3r commented on src/guide/glossary.md
> +This idea found its reflection in the blockchain-based systems that can check the stored data for validity.
```suggestion
This idea is reflected in the blockchain-based systems that can check the stored data for validity.
```

2023-01-03 13:59 UTC, WRRicht3r commented on src/guide/glossary.md
> +While the word itself means a valuable object, with blockchain being involved, we'll be talking about a representation of a valuable object on the blockchain.
```suggestion
While the word itself means "a valuable object," with blockchain being involved, we are referring to the representation of a valuable object on the blockchain.
```

2023-01-03 13:59 UTC, WRRicht3r commented on src/guide/glossary.md
> +Such assets can be easily swapped with other assets of the same type, because they are interchangeable.
```suggestion
Such assets can be easily swapped for other assets of the same type because they are interchangeable.
```

2023-01-04 08:18 UTC, outoftardis commented on src/guide/glossary.md
> +These are named after old-fashioned books used for financial records[^1] because of their history.
```suggestion
These are named after old-fashioned books that were used for financial records such as prices, news, and transaction information.
```

2023-01-04 08:18 UTC, outoftardis commented on src/guide/glossary.md
> +While the word itself means a valuable object, with blockchain being involved, we'll be talking about a representation of a valuable object on the blockchain.
```suggestion
In the context of blockchains, an asset is the representation of a valuable object on the blockchain.
```

2023-01-09 07:29 UTC, outoftardis approved these changes

2023-01-09 07:29 UTC, merged