[docs] #261: Update Bash tutorial: key pair generation before
hyperledger/iroha-2-docs pull request #264
Opened 2023-02-24 07:43 UTC by outoftardis

- Update Bash tutorial (Closes #261)
- Move some of the info about key generation to the section about keys
- Fix formatting

2023-02-24 09:02 UTC, WRRicht3r requested changes

2023-02-24 09:02 UTC, WRRicht3r commented on src/guide/configure/keys.md
> +the program somewhere convenient e.g. `/bin` for system-wide use you need
```suggestion
the program somewhere convenient e.g. `/bin` for system-wide use, you need
```

2023-02-24 09:12 UTC, WRRicht3r approved these changes

2023-03-02 11:22 UTC, 6r1d approved these changes
Everything is good, but I have a small expansion request that will be helpful to the users in our community.

2023-03-02 11:22 UTC, 6r1d commented on src/guide/bash.md
>  [configuring the corresponding parameters](#_1-iroha-2-client-setup).
Similarly to https://github.com/hyperledger/iroha-2-docs/issues/275, a piece of text that explains both peer AND client config may be useful here. If we have included in this Markdown flavour, a section will be copied among the several tutorial instances.

2023-03-02 12:12 UTC, merged