Merge branch 'master' of github.com:hyperledger/iroha-2-docs
hyperledger/iroha-2-docs pull request #28
Opened 2022-03-18 11:05 UTC by appetrosyan

Signed-off-by: Aleksandr <a-p-petrosyan@yandex.ru>Signed-off-by: Aleksandr <a-p-petrosyan@yandex.ru>

2022-03-18 15:06 UTC, WRRicht3r requested changes

2022-03-18 15:06 UTC, WRRicht3r commented on src/guide/advanced/triggers.md
> +This gets us nowhere, and a big problem in our current API, that we're trying to solve. Instead we should work bottom up.
```suggestion
This gets us nowhere and is a big problem in our current API, that we're trying to solve. Instead, we should work bottom-up.
```

2022-03-18 15:06 UTC, WRRicht3r commented on src/guide/advanced/triggers.md
> +and finally create an instance of a `Trigger`.
```suggestion
and then create an instance of a `Trigger`.
```

2022-03-18 15:06 UTC, WRRicht3r commented on src/guide/advanced/triggers.md
> +Finally in order to get said trigger onto the blockchain, we create a transaction with the following single instruction.
```suggestion
Finally, in order to get said trigger onto the blockchain, we create a transaction with the following single instruction.
```

2022-03-18 15:06 UTC, WRRicht3r commented on src/guide/advanced/triggers.md
> +Now, each time alice drinks some tea, the Mad Hatter will pour in a whole new cup. The keen eyed among you will see that the amount that alice drinks is irrelevant to how much tea will be transferred
```suggestion
Now, each time Alice drinks some tea, the Mad Hatter will pour in a whole new cup. The keen-eyed among you will see that the amount that Alice drinks is irrelevant to how much tea will be transferred. So Alice may well take a sip and be poured a whole new cup's worth.
```

2022-03-21 07:06 UTC, 0x009922 commented
Why is it located in `advanced` dir? Why not in the appendix one?

Anyway, you should add an appropriate record into the sidebar links list. It is here:

https://github.com/hyperledger/iroha-2-docs/blob/f074c7aa0f3f40bd7a8b77d6fb7f3bcf705b8869/.vitepress/config.ts#L30-L101

2022-03-21 15:44 UTC, appetrosyan commented on src/guide/advanced/triggers.md
> +A filter is what determines the _kind_ of trigger that you're dealing with. All triggers respond to events, but differently, and that difference  comes from the `EventFilter`. The reason for this arc
Rephrased.

2022-03-21 16:02 UTC, appetrosyan commented on src/guide/advanced/triggers.md
> +All triggers are event triggers in a sense. But the events in question are the ones that you'd get once something interesting happened in the blockchain: an asset got minted, an account got registere
Reworded.

2022-03-21 16:02 UTC, appetrosyan commented on src/guide/advanced/triggers.md
> +It's good in that you don't need to worry about registering your trigger in the proper name-space (for now), but it also means that your trigger processes almost every event in the blockchain.
Removed.

2022-03-21 16:14 UTC, appetrosyan commented on src/guide/advanced/triggers.md
> +Now, each time alice drinks some tea, the Mad Hatter will pour in a whole new cup. The keen eyed among you will see that the amount that alice drinks is irrelevant to how much tea will be transferred
Reworded

2022-03-21 16:57 UTC, merged