Metadata and store assets
hyperledger/iroha-2-docs pull request #318
Opened 2023-04-21 07:59 UTC by 6r1d

Part of https://github.com/hyperledger/iroha-2-docs/issues/308

2023-04-21 08:06 UTC, 6r1d commented
I have a question on the topic of this document. I want to tell what could be helpful for our users in this list of possible values for `Value`, which is key for the `Store` `AssetDefinition` instances.

Those are possible values. Which ones should I add, and which ones can I ignore, besides strings, booleans and numbers?

* Bool
* String
* Name
* LimitedMetadata
* MetadataLimits
* TransactionLimits
* LengthLimits
* Id
* Identifiable
* PublicKey
* SignatureCheckCondition
* TransactionValue
* TransactionQueryResult
* PermissionToken
* Hash
* Block
* BlockHeader
* Ipv4Addr
* Ipv6Addr
* Numeric
* Validator

2023-04-21 11:58 UTC, outoftardis commented on src/guide/configure/metadata-and-store-assets.md
> +You must use a `Store` asset if the data exists in the blockchain and a default number type is not applicable. It lets you record data sequences and works as a dictionary, where the keys are string,
```suggestion
You must use a `Store` asset if the data exists in the blockchain and a default number type is not applicable. It lets you record data sequences and works as a dictionary, where the keys are strings, while the values are  `Value` type instances that assume many types from `String` to `Ipv6Addr`.
```

2023-04-21 14:04 UTC, 6r1d commented on src/guide/configure/metadata-and-store-assets.md
> +You must use a `Store` asset if the data exists in the blockchain and a default number type is not applicable. It lets you record data sequences and works as a dictionary, where the keys are string,
Thanks!

2023-04-21 15:59 UTC, WRRicht3r requested changes

2023-04-21 15:59 UTC, WRRicht3r commented on src/guide/configure/metadata-and-store-assets.md
> +The `Store` assets and `metadata` allow storing several parameters with different types and have string keys. Despite the similarity, their use cases differ.
```suggestion
The `Store` and `metadata` assets allow for the storage of several parameters with different types and string keys. Despite the similarity, their use cases differ.
```

2023-04-21 15:59 UTC, WRRicht3r commented on src/guide/configure/metadata-and-store-assets.md
> +You must use `metadata` when you don’t want sequences of records, for example, extending user data. You’ll extend its `metadata` when you need to store something intended to be added to a specific `A
```suggestion
You must use `metadata` when you don’t want sequences of records, for example, extending user data. You can extend its `metadata` when you need to store something intended to be added to a specific `Account` or `Domain` instance.
```

2023-04-21 15:59 UTC, WRRicht3r commented on src/guide/configure/metadata-and-store-assets.md
> +Let’s say you have a clinic. Here, generic user data, such as birthdays, can be added to the `metadata`. The `Store` asset instances record the appointments, treatments suggested by the doctors, and
```suggestion
Let’s say, for example, you have a clinic. Here, generic user data, such as birthdays, can be added to `metadata`. The `Store` asset instances record the appointments, treatments suggested by the doctors, and medical test results.
```

2023-04-27 04:44 UTC, 0x009922 commented on .vitepress/config.ts
> +              link: '/guide/configure/metadata-and-store-assets.md',
```suggestion
              link: '/guide/configure/metadata-and-store-assets',
```

2023-05-03 04:39 UTC, 0x009922 approved these changes
Config LGTM

2023-05-03 07:34 UTC, WRRicht3r approved these changes

2023-05-03 07:35 UTC, merged