[docs] Introducing 'Security' section
hyperledger/iroha-2-docs pull request #374
Opened 2023-08-14 17:55 UTC by yamkovoy

PR #332 has been split for the sake of granularity.

Changes:
- Original PR #332 turned into the 'Security' section.
- Original topics restructured.
- Additional information added.

2023-08-21 12:55 UTC, WRRicht3r requested changes

2023-08-21 12:55 UTC, WRRicht3r commented on src/guide/security/storing-cryptographic-keys.md
> +For instructions on how to set up KeePassXC to ee [Configuring KeePassXC](#configuring-keepassxc) below.
```suggestion
For instructions on how to set up KeePassXC see the [Configuring KeePassXC](#configuring-keepassxc) section below.
```

2023-08-21 18:58 UTC, appetrosyan requested changes

2023-08-21 18:58 UTC, appetrosyan commented on src/guide/security/generating-cryptographic-keys.md
> +```
```suggestion

::: info Note

This trick works on most GNU Linux distributions, but is not guaranteed to do so. In order to have the desired effect please do the following:

1. Ensure that the directory exists, easiest method to do so is to run 
```bash
mkdir -p ~/.local/bin
```
If this command fails, you have an exotic permissions set up and should consult your systems administrator (or look for an answer online). 

2. Ensure that the `PATH` environment variable exported into your current shell  contains the directory `~/.local/bin`. 

There are multiple ways of doing that, 

<details> for `zsh` (default on Mac OS)
The [Arch Wiki](https://wiki.archlinux.org/title/Zsh#Configuring_$PATH) states that the best way to configure the `PATH` variable is by modifying the `.zshenv` file:
```zsh
typeset -U path PATH
path=(~/.local/bin $path)
export PATH
```

While the same statements can be added to `.zshrc` they do not belong there and will be overridden by e.g. `oh-my-zsh` and other package distributions. 
</details>


<details> on `fish`
The friendly interactive shell has the simplest method for adding directories to the `PATH` variable. 

```fish
fish_add_path ~/.local/bin
```
removing this from `PATH` may be problematic, as it is not a one-to-one correspondence as with other POSIX-compliant shells. 
</details>

<details> for `bash`

For the longest time the Bourne again shell was considered the standard POSIX-compliant shell for UNIX-like operating systems. It _is_ the default on many GNU Linux distributions with very few notable exceptions (Arch Linux). To add the path to `PATH`, execute the following:

```bash
echo 'export PATH=~/.local/bin:$PATH' >> ~/.bash_profile
```
which will be read automatically. 

</details>

In addition to the above methods, please consult the shell manual or consider adding the `PATH` variant to the terminal session configuration. 
:::

```

2023-08-21 20:28 UTC, appetrosyan commented on src/guide/security/operational-security.md
> +
```suggestion
- Avoid using browsers with known bad security models. Specifically
  * Chrome (proprietary)
  * Safari (proprietary, WebKit known to have fundamental security problems)
  * Opera (proprietary, known to leak data)
  * Firefox (known to leak data and pre-install questionable extensions)
  * Vivaldi (proprietary)
  * Edge (all of the above)
  * `surf` (extremely outdated)
- Prefer browsers with known good track records, and supporting user privacy and security first:
  * Librewolf, Icecat, Firedragon, _etc._.  -- Firefox forks with enhanced security features
  * Ungoogled chromium -- highly audited open source version of Chrome, 
  * Brave -- highly audited, adblock browser with privacy enhancing features
  * Falkon -- known good track record of security. All plugins come from the KDE store
  * Qutebrowser -- known good track record of security. The preferred browser of many security specialists. 
  
- Avoid enabling Java Script unless necessary. 

- Use the browser's built-in confinement mechanism for plugins. 

- Clear cookies before and after important operations. Avoid the "keep me signed in" style of buttons. 

- Enable ad-block features. These protect against more than just advertisements, and disable site tracking features. 

- Be mindful of lookalike characters (`0` and `O` and `О` are three different characters), make sure that you're able to spot them in a URL. 
```

2023-08-21 20:34 UTC, appetrosyan commented on src/guide/security/security-principles.md
> +
```suggestion
    - Avoid using SMS as a second factor. 
```

2023-08-21 20:34 UTC, appetrosyan commented on src/guide/security/security-principles.md
> +    - Utilize strong and unique passwords for all accounts.
```suggestion
    - Utilise strong and unique passwords for all accounts.
```

2023-08-21 20:37 UTC, appetrosyan commented on src/guide/security/security-principles.md
> +
```suggestion
    - Set up an email client to sign and verify signatures of all the received emails.  While it is possible to impersonate the sender's address and even pose as a bank, it is not possible to fake a signature. 
```

2023-08-21 20:38 UTC, appetrosyan commented on src/guide/security/security-principles.md
> +    - Be careful with email attachments and suspicious links, these could be phishing or malware attempts that aim to trick you or harm your device. Make sure you know who sent the email and that the
```suggestion
    - Disable both HTML messages and loading of external resources from unknown or unverified addresses. 
```

2023-08-21 20:39 UTC, appetrosyan commented on src/guide/security/security-principles.md
> +    - Learn about common phishing techniques to recognize and avoid suspicious emails, links, and requests for personal information.
```suggestion
    - Learn about common phishing techniques to recognise and avoid suspicious emails, links, and requests for personal information.
```

2023-08-21 20:39 UTC, appetrosyan commented on src/guide/security/security-principles.md
> +## Security Principles for Organizations
```suggestion
## Security Principles for Organisations
```

2023-08-21 20:39 UTC, appetrosyan commented on src/guide/security/security.md
Why empty file?

2023-08-21 20:47 UTC, appetrosyan commented on src/guide/security/storing-cryptographic-keys.md
I've not reviewed this file in full, because it was likely written in close collaboration with @6r1d.

2023-08-22 05:09 UTC, 0x009922 reviewed
This PR cannot be built, and has a set of issues when you look into it in a rendered view. I would mark this PR as draft, and would like to solve some technical problems.

2023-08-22 05:09 UTC, 0x009922 commented on src/guide/security/generating-cryptographic-keys.md
> +::: details Note
Please, do not use spoilers with a good reason.

```suggestion
::: tip
```

2023-08-22 05:33 UTC, 0x009922 commented
Also, there are references of KeePassXC screenshots, but the screenshots themselves do not exist.

2023-08-22 06:02 UTC, 6r1d requested changes

2023-09-18 08:08 UTC, Arjentix commented on src/guide/security/keys-for-network-deployment.md
> +:::
I checked the code and I can see that this check still exists inside Iroha Core, not inside Executor/Validator. So it's still true. I think we should left it as is

2023-09-19 08:44 UTC, WRRicht3r approved these changes
Approved pending all comments are addressed. 
Thanks

2023-09-25 12:28 UTC, yamkovoy reviewed
Addressed comments in commit 90e2f587446a1717daf0b7fa40c322f19d02738c

2023-09-25 12:58 UTC, yamkovoy reviewed
Reviewed and addressed

2023-10-23 13:28 UTC, outoftardis commented
since there is now #416, should this pr be closed?

2023-10-26 09:38 UTC, closed without merging