[feature] #306: Validate links post-build
hyperledger/iroha-2-docs pull request #405
Opened 2023-09-13 01:34 UTC by 0x009922

Closes #306

2023-09-13 05:40 UTC, 6r1d approved these changes
LGTM

2023-09-13 06:37 UTC, WRRicht3r requested changes

2023-09-13 06:37 UTC, WRRicht3r commented on src/guide/advanced/running-iroha-on-bare-metal.md
>      `configs/peer/config.json`.
```suggestion
    `configs/peer/config.json` file.
```

2023-09-13 06:37 UTC, WRRicht3r commented on src/guide/blockchain/data-model.md
>  ::: details Language-specific guidance on registering these objects
```suggestion
::: details Language-specific guides to register these objects
```

2023-09-13 06:37 UTC, WRRicht3r commented on src/guide/build.md
>      If you're having issues with installing Rust compatible with our code
```suggestion
    If you're having issues installing Rust compatible with our code
```

2023-09-13 06:37 UTC, WRRicht3r commented on src/guide/configure/peer-configuration.md
> +- [Public and private keys for the peer](#public-and-private-keys) (`PUBLIC_KEY` and
```suggestion
- [The peer's Public and private keys](#public-and-private-keys) (`PUBLIC_KEY` and
```

2023-09-13 06:37 UTC, WRRicht3r commented on src/guide/glossary.md
>  `Sequence`. They are mostly used by
```suggestion
`Sequence`. They are mostly used as
```

2023-09-14 02:36 UTC, 0x009922 commented
@WRRicht3r, this PR is focused on functional changes and related documentation fixes. While I appreciate your suggestions on doc strings, they are technically outside the scope of this PR. I have included them this time, but in the future, I would prefer to keep PRs more granular.

2023-09-14 08:02 UTC, merged