[docs]: add SCALE codec troubleshooting section (#428)
hyperledger/iroha-2-docs pull request #429
Opened 2023-11-09 15:16 UTC by 6r1d

As discussed with @mversic, we need to add a SCALE codec-related troubleshooting section.

2023-11-09 16:09 UTC, WRRicht3r requested changes

2023-11-09 16:09 UTC, WRRicht3r commented on src/guide/troubleshooting/configuration-issues.md
> +between how the data is structured on the client and the peer sides.
```suggestion
between the data structure on the client and the peer sides.
```

2023-11-09 16:09 UTC, WRRicht3r commented on src/guide/troubleshooting/configuration-issues.md
> +In case you're using `iroha_client_cli` and rebuild it inside the Iroha
```suggestion
In case you're using the `iroha_client_cli` and rebuild it inside the Iroha
```

2023-11-09 16:09 UTC, WRRicht3r commented on src/guide/troubleshooting/configuration-issues.md
> +project directory root:
```suggestion
project directory root, use these commands:
```

2023-11-09 16:09 UTC, WRRicht3r commented on src/guide/troubleshooting/configuration-issues.md
> +You need to view the part at which the Iroha peer starts.
```suggestion
You need to view the part where the Iroha peer starts.
```

2023-11-09 16:09 UTC, WRRicht3r commented on src/guide/troubleshooting/configuration-issues.md
> +If you are using one of our SDKs, please make sure to update it.
```suggestion
If you are using one of our SDKs, please make sure it is up to date.
```

2023-11-10 12:27 UTC, outoftardis commented on src/guide/troubleshooting/configuration-issues.md
> +* `cargo build -p iroha_client_cli`
this should be a code block, not a list

2023-11-13 04:45 UTC, 0x009922 requested changes

2023-11-13 04:45 UTC, 0x009922 commented on src/guide/troubleshooting/configuration-issues.md
> +You need to view the part where the Iroha peer starts.
> You need to view the part where the Iroha peer starts.

Which part? Provide an example.

2023-11-13 04:45 UTC, 0x009922 commented on src/guide/troubleshooting/configuration-issues.md
> +If you are using one of our SDKs, please make sure it is up to date.
It should be not necessarily up to date, but the version of SDK should be compatible with the version of Iroha. In order to check it, it is generally recommended to check for the version in the SDKs readme.

2023-11-13 04:45 UTC, 0x009922 commented on src/guide/troubleshooting/configuration-issues.md
> +* `cargo build -p iroha_client_cli`
```suggestion
* `cargo build -p iroha_client_cli --release`
```

2023-11-13 04:45 UTC, 0x009922 commented on src/guide/troubleshooting/configuration-issues.md
> +`/target/debug/iroha_client_cli --version` with a version in the Iroha log.
```suggestion
`cargo run -p iroha_client_cli --release -- --version` with a version in the Iroha log.
```

2023-11-13 04:45 UTC, 0x009922 commented on src/guide/troubleshooting/configuration-issues.md
> +between the data structure on the client and the peer sides.
I would rephrase. SCALE codec errors appear when the versions of the data structures differ between the client and the peer sides.

2024-06-27 08:42 UTC, closed without merging