[documentation]: Review peer and client configurations
hyperledger/iroha-2-docs pull request #58
Opened 2022-05-25 12:32 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

Reviewed two more topics, addressing #43

2022-05-30 09:20 UTC, WRRicht3r requested changes

2022-05-30 09:20 UTC, WRRicht3r commented on src/guide/configure/peer-configuration.md
> +The remaining options are for tuning Iroha, so you don't need to worry
```suggestion
The remaining options are for fine-tuning Iroha, so you don't need to worry
```

2022-05-30 09:20 UTC, WRRicht3r commented on src/guide/configure/peer-configuration.md
> +to do. Want only messages from a specific module or package? You can do
```suggestion
to do. Do you only want messages from a specific module or package? You can do
```

2022-05-31 07:40 UTC, appetrosyan approved these changes

2022-05-31 07:40 UTC, appetrosyan commented on src/guide/configure/peer-configuration.md
> +- `INFO` (the default)
```suggestion
- `INFO` (the default)
- `WARN` (log everything that could be an error)
```

2022-05-31 07:41 UTC, merged