[documentation]: Review the Queries chapter
hyperledger/iroha-2-docs pull request #66
Opened 2022-06-02 05:15 UTC by outoftardis

Signed-off-by: Ekaterina Mekhnetsova <mekkatya@gmail.com>

2022-06-02 05:16 UTC, outoftardis commented on src/guide/advanced/queries.md
> +  great care.
I don't think we follow this scheme precisely as we claim to do

2022-06-02 07:05 UTC, WRRicht3r requested changes

2022-06-02 07:05 UTC, WRRicht3r commented on src/guide/advanced/queries.md
> +An optional feature. Be default, it is present on all Iroha 2 deployments
```suggestion
An optional feature. By default, it is present on all Iroha 2 deployments
```

2022-06-07 12:34 UTC, outoftardis commented on src/guide/advanced/queries.md
> +- _returns_ means that the query has the data readily available, just as
```suggestion
- _returns_ or _finds_ mean that the query has the data readily available, just as
```

2022-06-07 12:41 UTC, WRRicht3r approved these changes

2022-06-08 11:15 UTC, appetrosyan approved these changes

2022-06-08 11:15 UTC, merged