[documentation]: Review language-specific guides
hyperledger/iroha-2-docs pull request #70
Opened 2022-06-07 10:59 UTC by outoftardis

2022-06-07 11:04 UTC, outoftardis commented on src/guide/rust.md
> -odd error messages, that's because you didn't call `build()` at the end.
I think this part is unnecessary due to #53

2022-06-07 11:06 UTC, outoftardis commented on src/guide/python.md
@appetrosyan line 5: is that still true?

2022-06-07 11:40 UTC, WRRicht3r commented on src/guide/bash.md
> +make do with what one has.
🫶

2022-06-07 12:09 UTC, WRRicht3r requested changes

2022-06-07 12:09 UTC, WRRicht3r commented on src/guide/rust.md
> +Needless to say that a synchronous infinite blocking loop is bad UX for
```suggestion
Needless to say, an synchronous infinite blocking loop is bad UX for
```

2022-06-07 12:16 UTC, outoftardis commented on src/guide/kotlin-java.md
> +Without further ado, here's an example `build.gradle` file:
```suggestion
Without further ado, here's the example `build.gradle` file:
```

2022-06-07 12:34 UTC, WRRicht3r approved these changes

2022-06-08 11:22 UTC, appetrosyan approved these changes

2022-06-08 11:22 UTC, merged